#!/bin/sh

case $1 in
	mem)  free -h | awk '/^Mem/ { print $3"/"$2 }' | sed s/i//g ;;
	date) date +'%a %b %-d, %-I:%M %p' ;;
	wttr) curl wttr.in\?format="+%c+%t\n" | awk '{$1=$1};1' || echo '❔ ...' ;;
esac
