#!/bin/sh
# ssh wrapper

# config file
ARGS=-F"$XDG_CONFIG_HOME"/ssh/config

# identity file
ARGS="$ARGS "-i"$XDG_DATA_HOME"/ssh/id_rsa

# pass arguments
ARGS="$ARGS $@"

# run ssh
/usr/bin/"`basename $0`" "$ARGS"
