#!/bin/sh
# steam wrapper

# update home directory
export HOME="$XDG_DATA_HOME"/Steam

# update data directory
export XDG_DATA_HOME="$XDG_DATA_HOME"/Steam/`basename "$XDG_DATA_HOME"`

# launch steam
/usr/bin/steam $@
