#!/bin/sh
# launches a game from the Command & Conquer The First Decade collection

export STEAM_COMPAT_DATA_PATH="$XDG_DATA_HOME"/proton/tfd
ROOTPATH="$STEAM_COMPAT_DATA_PATH"/pfx/drive_c/'Program Files (x86)'/'EA Games'/'Command & Conquer The First Decade'
GAMES="`find "$ROOTPATH" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | grep 'Command & Conquer'`\nCommand & Conquer Red Alert(tm) II Yuri's Revenge"

# select desired game
GAME=$2
while [ -z "$GAME" ] || [ ! -d "$ROOTPATH"/"$GAME" ]; do
	GAME=`echo "$GAMES" | dmenu -p "$(basename "$ROOTPATH")"`
	[ $? -ne 0 ] && exit $?
	# Yuri's Revenge is a special case
	[ "$GAME" = "Command & Conquer Red Alert(tm) II Yuri's Revenge" ] && break
done

# format game path
case "$GAME" in
	# Yuri's Revenge uses RA2 game directory
	*Yuri*) GAMEPATH="$ROOTPATH"/'Command & Conquer Red Alert(tm) II' ;;
	# every other game is normal
	*) GAMEPATH="$ROOTPATH"/"$GAME" ;;
esac

# format game executable
GAMEEXEC=
case "$GAME" in
	# Tiberian Sun / Red Alert 2 (+ Yuri's Revenge)
	# these games have subdirectories
	*'Tiberian Sun(tm)'|*'Red Alert(tm) II'*)
		case "$GAME" in
			# Tiberian Sun
			*Sun*)
				GAMEPATH="$GAMEPATH"/SUN
				GAMEEXEC=SUN.exe
			;;
			# Yuri's Revenge
			*Yuri*)
				GAMEPATH="$GAMEPATH"/RA2
				GAMEEXEC=RA2MD.exe
			;;
			# Red Alert 2
			*)
				GAMEPATH="$GAMEPATH"/RA2
				GAMEEXEC=RA2.exe
			;;
		esac
	;;
	# Generals (+ Zero Hour)
	*Generals*) GAMEEXEC=generals.exe ;;
	# Red Alert 1995
	*'Red Alert(tm)') GAMEEXEC=ra95.exe ;;
	# Command & Conquer 1995
	*) GAMEEXEC=C\&C95.exe ;;	
esac

# launch game
proton "$GAMEPATH"/"$GAMEEXEC"
