#!/bin/sh

case $1 in
	# set volume
	toggle) pamixer -t   && pkill -RTMIN+10 dwmblocks ;;
	on)     pamixer -u   && pkill -RTMIN+10 dwmblocks ;;
	off)    pamixer -m   && pkill -RTMIN+10 dwmblocks ;;
	up)     pamixer -i 5 && pkill -RTMIN+10 dwmblocks ;;
	down)   pamixer -d 5 && pkill -RTMIN+10 dwmblocks ;;

	# get volume
	get)
		OUT=`pamixer --get-volume-human`
		case $OUT in
			muted) echo -n 🔇\ `pamixer --get-volume`% ;;
			*)     echo -n 🔊 "$OUT"
		esac
	;;

	# errors
	"") >&2 echo 'No command given'     && exit 1 ;;
	*)  >&2 echo "Unknown command '$1'" && exit 1
esac
